"""
NetLogo commands and reporters used in the simulation
"""

NETLOGO_VERSION = "5"

TURTLE_PRESENT_REPORTER = "count turtles"
EVACUATED_REPORTER = "number_passengers - count agents + 1"
DEAD_REPORTER = "count agents with [ st_dead = 1 ]"
SEED_SIMULATION_REPORTER = "seed-simulation {}"

SET_SIMULATION_ID_COMMAND = 'set SIMULATION_ID "{}"'
SET_STAFF_SUPPORT_COMMAND = "set REQUEST_STAFF_SUPPORT {}"
SET_PASSENGER_SUPPORT_COMMAND = "set REQUEST_BYSTANDER_SUPPORT {}"
SET_FALL_LENGTH_COMMAND = "set DEFAULT_FALL_LENGTH {}"
SET_FRAME_GENERATION_COMMAND = "set ENABLE_FRAME_GENERATION {}"
SET_FALL_LENGTH_COMMAND = "set DEFAULT_FALL_LENGTH {}"
SET_FALL_CHANCE_COMMAND = "set FALL_CHANCE {}"

SET_NUM_OF_ROBOTS_COMMAND = "set NUM_OF_ROBOTS {}"
SET_NUM_OF_PASSENGERS_COMMAND = "set NUM_OF_PASSENGERS {}"
SET_NUM_OF_STAFF_COMMAND = "set NUM_OF_STAFF {}"
SET_ROOM_ENVIRONMENT_TYPE = "set ROOM_ENVIRONMENT_INDX {}"

ENABLE_STAFF_COMMAND = SET_STAFF_SUPPORT_COMMAND.format("TRUE")
ENABLE_PASSENGER_COMMAND = SET_PASSENGER_SUPPORT_COMMAND.format("TRUE")
ENABLE_FRAME_GENERATION_COMMAND = SET_FRAME_GENERATION_COMMAND.format("TRUE")
